name: Prettier By RizzyFuzz
on: 
  push:
    branches:
      - main
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - run: npm i -g prettier
      - run: prettier --write '**/*.{js,json}'
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic Tidy Up Code
          branch: ${{ github.head_ref }}


          
